# -*- coding: utf-8 -*-
"""example_a0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSiTX4ZuwYsTYcLqu4378lEi2eBEjREO

# BBM409 Assignment_0

Student ID:21327881

Name Surname:Talha Dede
"""

import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

data = files.upload()

"""## Pre-processing"""

#Read the uploaded file into a Pandas DataFrame
file_name = list(data.keys())[0]

df = pd.read_excel(io.BytesIO(data[file_name]))

print("First 5 rows of the dataset:")
display(df.head())

# Separate Features (X) and Target (y)
# The 'Class' column contains the bean types (SEKER, BARBUNYA, etc.)
X = df.drop('Class', axis=1)
y = df['Class']

# Encode Target Variable
# Convert string class labels into numeric values (0 to 6)
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

print("\nTarget is encoded successfully.")
print("\nClass mapping (for reference):")
for i, item in enumerate(encoder.classes_):
    print(f"{item} --> {i}")

"""1. **Feature Scaling (`StandardScaler`):** I applied `StandardScaler` to normalize the numerical features. This is an essential step because distance-based algorithms like k-NN and SVM rely on calculating the Euclidean distance between data points. If the features are left unscaled, those with significantly larger numeric ranges (e.g., Area) would disproportionately dominate the distance calculations over features with smaller ranges (e.g., Compactness), leading to biased and inaccurate models.
2. **Target Encoding (`LabelEncoder`):** I used `LabelEncoder` to transform the categorical target variable ('Class', which contains string labels like SEKER, BARBUNYA) into numeric values. This is necessary because Scikit-Learn's classification algorithms require numerical target arrays to function properly.

## Split the dataset

We split the dataset into three sets: training (70%), validation (10%), and testing (20%). This 70-10-20 split allows us to train the models, tune parameters using the validation set, and finally evaluate the performance on an independent test set. **Crucially, to prevent Data Leakage, we applied Feature Scaling (StandardScaler) ONLY AFTER splitting the data, fitting it exclusively on the Training set.**
"""

# Split the dataset into 80% Temporary (Train + Val) and 20% Test sets.
#(Using 'X' directly to prevent data leakage before scaling)
X_temp, X_test, y_temp, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Split the remaining 80% subset into 70% Train and 10% Validation sets.
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.125, random_state=42)

# Feature Scaling
# Distance-based algorithms (like k-NN, SVM) require features to be scaled
scaler = StandardScaler()

# Fit ONLY on the training data to learn the rules
X_train = scaler.fit_transform(X_train)

# Transform the other sets using the learned rules
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)
X_temp = scaler.transform(X_temp) #for 5-Fold CV

print("Pre-processing is complete! Features are scaled AFTER splitting.")
print("X_train (Training - 70%) shape:", X_train.shape)
print("X_val (Validation - 10%) shape:", X_val.shape)
print("X_test (Testing - 20%) shape:", X_test.shape)

"""## Classification Methods

In this homework, we use kNN, Naive Bayes, SVM and Random Forest

### kNN
"""

# k values to try
k_values = [1, 3, 5, 7, 9, 11, 13, 15]
val_accuracies = []

# Loop to find the best k
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_val_pred = knn.predict(X_val)
    acc = accuracy_score(y_val, y_val_pred)
    val_accuracies.append(acc)
    print(f"k={k} -> Validation Accuracy: {acc:.4f}")

#Plotting the results
plt.figure(figsize=(10, 5))
plt.plot(k_values, val_accuracies, marker='o', linestyle='--', color='b')
plt.title('kNN: Accuracy vs. k Value')
plt.xlabel('Number of Neighbors (k)')
plt.ylabel('Validation Accuracy')
plt.xticks(k_values)
plt.grid(True)
plt.show()

# Select the best k
best_k = k_values[val_accuracies.index(max(val_accuracies))]
print(f"\nBest k value based on validation set: {best_k}")

"""kNN Hyperparameter Tuning : To find the optimal number of neighbors ($k$), we evaluated several values ranging from $1$ to $15$ using the Validation Set. As shown in the plot above, the model's performance varies with different $k$ values. To ensure the highest possible accuracy, we dynamically selected the best-performing $k$ value based on the validation results. This optimal $k$ was then used for the weighted k-NN model and final evaluations. This approach allows the model to adapt to the data's specific structure, preventing underfitting or overfitting and ensuring robust generalization to new data."""

# 1. Implementing Weighted k-NN as requested in the instructions
# We use our dynamically selected best_k (determined in the tuning step)
weighted_knn = KNeighborsClassifier(n_neighbors=best_k, weights='distance')
weighted_knn.fit(X_train, y_train)
y_val_pred_weighted = weighted_knn.predict(X_val)

print(f"--- Weighted k-NN (k={best_k}) Performance ---")
print(f"Weighted Validation Accuracy: {accuracy_score(y_val, y_val_pred_weighted):.4f}\n")

# 2. Detailed Metrics (Precision, Recall, F1)
# Using the optimal k value
print(f"--- Classification Report for kNN (k={best_k}) ---")
print(classification_report(y_val, y_val_pred, target_names=encoder.classes_))

# 3. Confusion Matrix
# The title is now also dynamic
cm = confusion_matrix(y_val, y_val_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=encoder.classes_)
fig, ax = plt.subplots(figsize=(10, 8))
disp.plot(cmap='Blues', ax=ax, xticks_rotation='vertical')
plt.title(f'Confusion Matrix: kNN (k={best_k})')
plt.show()

"""### Naive Bayes"""

# Initialize and train Naive Baye
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

# Predictions
y_val_pred_nb = nb_model.predict(X_val)

# Results
print(f"Naive Bayes Validation Accuracy: {accuracy_score(y_val, y_val_pred_nb):.4f}")
print("\n--- Naive Bayes Classification Report ---")
print(classification_report(y_val, y_val_pred_nb, target_names=encoder.classes_))

# Generate the confusion matrix for Naive Bayes
cm_nb = confusion_matrix(y_val, y_val_pred_nb)

# Plotting the matrix
disp_nb = ConfusionMatrixDisplay(confusion_matrix=cm_nb, display_labels=encoder.classes_)
fig, ax = plt.subplots(figsize=(10, 8))
disp_nb.plot(cmap='Reds', ax=ax, xticks_rotation='vertical')
plt.title('Confusion Matrix: Naive Bayes')
plt.show()

"""The Gaussian Naive Bayes model was implemented to classify the dry bean types. On the validation set, the model achieved an accuracy of 0.9008.

Key Observations:

Performance by Class: The model performs exceptionally well on the 'BOMBAY' class, achieving a perfect precision, recall, and F1-score of 1.00. This suggests that the features of Bombay beans are distinct and easily separable by a probabilistic model.


Independence Assumption: Naive Bayes is based on Bayes' theorem and assumes that features are conditionally independent. In our bean dataset, morphological features like Area and Perimeter are likely correlated. This violation of the independence assumption might explain why the accuracy (0.9008) is slightly lower than the kNN model (~0.93).


Confusion Matrix Analysis: The Confusion Matrix  visually reveals how the model distinguishes between bean types. For instance, we can observe slight confusion between similar classes like BARBUNYA and CALI.


Comprehensive Evaluation: Beyond simple accuracy, we reported Precision, Recall, and F1-score for each of the 7 bean classes. This provides a more robust understanding of the model's strengths and weaknesses across different categories.

###SVM
"""

# Testing different kernels for SVM
kernels = ['linear', 'rbf']
for kernel in kernels:
    svm_model = SVC(kernel=kernel)
    svm_model.fit(X_train, y_train)
    val_acc = svm_model.score(X_val, y_val)
    print(f"SVM with {kernel} kernel - Validation Accuracy: {val_acc:.4f}")

# Training SVM with RBF kernel (standard for this type of data)
svm_model = SVC(kernel='rbf')
svm_model.fit(X_train, y_train)
y_val_pred_svm = svm_model.predict(X_val)

print(f"SVM (RBF) Validation Accuracy: {accuracy_score(y_val, y_val_pred_svm):.4f}")

# Confusion Matrix for SVM
cm_svm = confusion_matrix(y_val, y_val_pred_svm)
disp_svm = ConfusionMatrixDisplay(confusion_matrix=cm_svm, display_labels=encoder.classes_)
fig, ax = plt.subplots(figsize=(8, 6))
disp_svm.plot(cmap='Greens', ax=ax, xticks_rotation='vertical')
plt.title('Confusion Matrix: SVM (RBF)')
plt.show()

"""SVM Analysis :
We evaluated the Support Vector Machine (SVM) model using both Linear and RBF kernels. The RBF kernel generally provided better results as it can capture non-linear relationships between morphological features. The high validation accuracy and the Confusion Matrix show that SVM is very effective at separating class boundaries, particularly for distinct bean types like BOMBAY.

###Random Forest
"""

# Testing different number of trees
n_estimators_list = [50, 100, 200]
for n in n_estimators_list:
    rf_model = RandomForestClassifier(n_estimators=n, random_state=42)
    rf_model.fit(X_train, y_train)
    val_acc = rf_model.score(X_val, y_val)
    print(f"Random Forest with {n} estimators - Validation Accuracy: {val_acc:.4f}")

# Training Random Forest with 100 trees
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_val_pred_rf = rf_model.predict(X_val)

print(f"Random Forest Validation Accuracy: {accuracy_score(y_val, y_val_pred_rf):.4f}")

# Confusion Matrix for Random Forest
cm_rf = confusion_matrix(y_val, y_val_pred_rf)
disp_rf = ConfusionMatrixDisplay(confusion_matrix=cm_rf, display_labels=encoder.classes_)
fig, ax = plt.subplots(figsize=(8, 6))
disp_rf.plot(cmap='Purples', ax=ax, xticks_rotation='vertical')
plt.title('Confusion Matrix: Random Forest')
plt.show()

"""Random Forest Analysis:
For the Random Forest classifier, we tested different numbers of estimators ($n=50, 100, 200$). This ensemble method is highly robust as it combines multiple decision trees to reduce overfitting. As seen in the results, Random Forest achieved one of the highest accuracies, correctly identifying complex bean structures with minimal confusion between similar classes.
"""

# Dictionary of models
models = {
    "kNN": KNeighborsClassifier(n_neighbors=best_k),
    "Naive Bayes": GaussianNB(),
    "SVM (RBF)": SVC(kernel='rbf'),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

print("--- 5-Fold Cross Validation (on X_temp) ---")
for name, model in models.items():
    cv_scores = cross_val_score(model, X_temp, y_temp, cv=5)
    print(f"{name} CV Mean Accuracy: {cv_scores.mean():.4f}")

print("\n--- FINAL TEST SET PERFORMANCE (on X_test) ---")
for name, model in models.items():
    model.fit(X_train, y_train) # Re-train on full train set
    test_acc = accuracy_score(y_test, model.predict(X_test))
    print(f"{name} Test Accuracy: {test_acc:.4f}")

"""###Final Evaluation & Conclusion
After conducting a comprehensive study with four different classification models, we observed the following professional insights based on our results:

Model Performance & SVM Superiority: SVM (with RBF Kernel) emerged as the top performer with an accuracy of approximately 93.17%. This was an expected outcome because the RBF kernel is exceptionally capable of mapping morphological features into a higher-dimensional space, allowing it to find optimal non-linear boundaries between complex bean classes that other models might struggle to separate.

Naive Bayes Insights: As anticipated, Naive Bayes provided the lowest performance (around 90.45%). This is a direct consequence of its "naive" assumption that all features are independent. In this dataset, features like Area, Perimeter, and EquivDiameter are naturally correlated. This violation of the independence assumption explains why it slightly lags behind more flexible models like SVM and Random Forest.

Model Stability & Generalization: The high consistency between our 5-Fold Cross Validation scores and the Final Test Set results (with test scores often being slightly higher) confirms that our models are stable and not overfitted. It also proves that our strategy of "Scaling after Splitting" was successful in preventing Data Leakage, ensuring the model's reliability on unseen data.

Final Verdict: All models achieved over 90% accuracy, indicating that the dry bean dataset is well-structured. However, for real-world applications requiring the highest precision, SVM (RBF) or Random Forest are the most suitable choices due to their ability to handle complex feature relationships.
"""